# .travis.yml
language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
cache: bundler
addons:
  postgresql: "9.4"
services:
  - postgresql
  - mongodb
  - redis
script:
  - xvfb-run -a bundle exec rake parallel:prepare[1]
  - xvfb-run -a bundle exec rake parallel:spec
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.travis.yml config/database.yml
  # - cp config/mongoid.travis.yml config/mongoid.yml
  - bundle exec rake db:drop db:create db:migrate
  # - RAILS_ENV=test parallel:prepare
#  - sh -c "psql -c 'DROP DATABASE IF EXISTS adiq_dev;' -U postgres"
#  - sh -c "psql -c 'DROP DATABASE IF EXISTS adiq_dev;' -U postgres"
