development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: adiq_dev
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: adiq_test_<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 25
  username: postgres
  password:
